# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d74b8ad6f21aad5bc4e34a67de988991c84252615e947fa3417176e7f16df5cc58337c5b707528ff3483cb2afef4dc991fe4714c7b8c8d8220c2902e1715f00

test:
  secret_key_base: 5fa438518c01d37b902989d69eef6c6164f9e576aff9772477050dd6488edec98fa2c7527308a0168cf56b3d2164f5b88eb625597af9609cd992cfcd460ec04a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
